from os import walk
from shutil import copyfile
from __builtin__ import staticmethod

class FontAwesome4To5:
    # the following search and replace is executed after the fa > fas replace
    FA_ICONS = {
        'fas fa-address-book-o': 'far fa-address-book',
        'fas fa-address-card-o': 'far fa-address-card',
        'fas fa-area-chart': 'fas fa-chart-area',
        'fas fa-arrow-circle-o-down': 'far fa-arrow-alt-circle-down',
        'fas fa-arrow-circle-o-left': 'far fa-arrow-alt-circle-left',
        'fas fa-arrow-circle-o-right': 'far fa-arrow-alt-circle-right',
        'fas fa-arrow-circle-o-up': 'far fa-arrow-alt-circle-up',
        'fas fa-arrows-alt': 'fas fa-expand-arrows-alt',
        'fas fa-arrows-h': 'fas fa-arrows-alt-h',
        'fas fa-arrows-v': 'fas fa-arrows-alt-v',
        'fas fa-arrows': 'fas fa-arrows-alt',
        'fas fa-asl-interpreting': 'fas fa-american-sign-language-interpreting',
        'fas fa-automobile': 'fas fa-car',
        'fas fa-bank': 'fas fa-university',
        'fas fa-bar-chart-o': 'far fa-chart-bar',
        'fas fa-bar-chart': 'far fa-chart-bar',
        'fas fa-bathtub': 'fas fa-bath',
        'fas fa-battery-0': 'fas fa-battery-empty',
        'fas fa-battery-1': 'fas fa-battery-quarter',
        'fas fa-battery-2': 'fas fa-battery-half',
        'fas fa-battery-3': 'fas fa-battery-three-quarters',
        'fas fa-battery-4': 'fas fa-battery-full',
        'fas fa-battery': 'fas fa-battery-full',
        'fas fa-bell-o': 'far fa-bell',
        'fas fa-bell-slash-o': 'far fa-bell-slash',
        'fas fa-bitbucket-square': 'fab fa-bitbucket',
        'fas fa-bitcoin': 'fab fa-btc',
        'fas fa-bookmark-o': 'far fa-bookmark',
        'fas fa-building-o': 'far fa-building',
        'fas fa-cab': 'fas fa-taxi',
        'fas fa-calendar-check-o': 'far fa-calendar-check',
        'fas fa-calendar-minus-o': 'far fa-calendar-minus',
        'fas fa-calendar-o': 'far fa-calendar',
        'fas fa-calendar-plus-o': 'far fa-calendar-plus',
        'fas fa-calendar-times-o': 'far fa-calendar-times',
        'fas fa-calendar': 'fas fa-calendar-alt',
        'fas fa-caret-square-o-down': 'far fa-caret-square-down',
        'fas fa-caret-square-o-left': 'far fa-caret-square-left',
        'fas fa-caret-square-o-right': 'far fa-caret-square-right',
        'fas fa-caret-square-o-up': 'far fa-caret-square-up',
        'fas fa-cc': 'far fa-closed-captioning',
        'fas fa-chain-broken': 'fas fa-unlink',
        'fas fa-chain': 'fas fa-link',
        'fas fa-check-circle-o': 'far fa-check-circle',
        'fas fa-check-square-o': 'far fa-check-square',
        'fas fa-circle-o-notch': 'fas fa-circle-notch',
        'fas fa-circle-o': 'far fa-circle',
        'fas fa-circle-thin': 'far fa-circle',
        'fas fa-clock-o': 'far fa-clock',
        'fas fa-close': 'fas fa-times',
        'fas fa-cloud-download': 'fas fa-cloud-download-alt',
        'fas fa-cloud-upload': 'fas fa-cloud-upload-alt',
        'fas fa-cny': 'fas fa-yen-sign',
        'fas fa-code-fork': 'fas fa-code-branch',
        'fas fa-comment-o': 'far fa-comment',
        'fas fa-commenting-o': 'far fa-comment-alt',
        'fas fa-commenting': 'fas fa-comment-alt',
        'fas fa-comments-o': 'far fa-comments',
        'fas fa-credit-card-alt': 'fas fa-credit-card',
        'fas fa-cutlery': 'fas fa-utensils',
        'fas fa-dashboard': 'fas fa-tachometer-alt',
        'fas fa-deafness': 'fas fa-deaf',
        'fas fa-dedent': 'fas fa-outdent',
        'fas fa-diamond': 'far fa-gem',
        'fas fa-dollar': 'fas fa-dollar-sign',
        'fas fa-dot-circle-o': 'far fa-dot-circle',
        'fas fa-drivers-license-o': 'far fa-id-card',
        'fas fa-drivers-license': 'fas fa-id-card',
        'fas fa-eercast': 'fab fa-sellcast',
        'fas fa-envelope-o': 'far fa-envelope',
        'fas fa-envelope-open-o': 'far fa-envelope-open',
        'fas fa-eur': 'fas fa-euro-sign',
        'fas fa-euro': 'fas fa-euro-sign',
        'fas fa-exchange': 'fas fa-exchange-alt',
        'fas fa-external-link-square': 'fas fa-external-link-square-alt',
        'fas fa-external-link': 'fas fa-external-link-alt',
        'fas fa-eyedropper': 'fas fa-eye-dropper',
        'fas fa-fa': 'fab fa-font-awesome',
        'fas fa-facebook-f': 'fab fa-facebook-f',
        'fas fa-facebook-official': 'fab fa-facebook',
        'fas fa-facebook': 'fab fa-facebook-f',
        'fas fa-feed': 'fas fa-rss',
        'fas fa-file-archive-o': 'far fa-file-archive',
        'fas fa-file-audio-o': 'far fa-file-audio',
        'fas fa-file-code-o': 'far fa-file-code',
        'fas fa-file-excel-o': 'far fa-file-excel',
        'fas fa-file-image-o': 'far fa-file-image',
        'fas fa-file-movie-o': 'far fa-file-video',
        'fas fa-file-o': 'far fa-file',
        'fas fa-file-pdf-o': 'far fa-file-pdf',
        'fas fa-file-photo-o': 'far fa-file-image',
        'fas fa-file-picture-o': 'far fa-file-image',
        'fas fa-file-powerpoint-o': 'far fa-file-powerpoint',
        'fas fa-file-sound-o': 'far fa-file-audio',
        'fas fa-file-text-o': 'far fa-file-alt',
        'fas fa-file-text': 'fas fa-file-alt',
        'fas fa-file-video-o': 'far fa-file-video',
        'fas fa-file-word-o': 'far fa-file-word',
        'fas fa-file-zip-o': 'far fa-file-archive',
        'fas fa-files-o': 'far fa-copy',
        'fas fa-flag-o': 'far fa-flag',
        'fas fa-flash': 'fas fa-bolt',
        'fas fa-floppy-o': 'far fa-save',
        'fas fa-folder-o': 'far fa-folder',
        'fas fa-folder-open-o': 'far fa-folder-open',
        'fas fa-frown-o': 'far fa-frown',
        'fas fa-futbol-o': 'far fa-futbol',
        'fas fa-gbp': 'fas fa-pound-sign',
        'fas fa-ge': 'fab fa-empire',
        'fas fa-gear': 'fas fa-cog',
        'fas fa-gears': 'fas fa-cogs',
        'fas fa-gittip': 'fab fa-gratipay',
        'fas fa-glass': 'fas fa-glass-martini',
        'fas fa-google-plus-circle': 'fab fa-google-plus',
        'fas fa-google-plus-official': 'fab fa-google-plus',
        'fas fa-google-plus': 'fab fa-google-plus-g',
        'fas fa-group': 'fas fa-users',
        'fas fa-hand-grab-o': 'far fa-hand-rock',
        'fas fa-hand-lizard-o': 'far fa-hand-lizard',
        'fas fa-hand-o-down': 'far fa-hand-point-down',
        'fas fa-hand-o-left': 'far fa-hand-point-left',
        'fas fa-hand-o-right': 'far fa-hand-point-right',
        'fas fa-hand-o-up': 'far fa-hand-point-up',
        'fas fa-hand-paper-o': 'far fa-hand-paper',
        'fas fa-hand-peace-o': 'far fa-hand-peace',
        'fas fa-hand-pointer-o': 'far fa-hand-pointer',
        'fas fa-hand-rock-o': 'far fa-hand-rock',
        'fas fa-hand-scissors-o': 'far fa-hand-scissors',
        'fas fa-hand-spock-o': 'far fa-hand-spock',
        'fas fa-hand-stop-o': 'far fa-hand-paper',
        'fas fa-handshake-o': 'far fa-handshake',
        'fas fa-hard-of-hearing': 'fas fa-deaf',
        'fas fa-hdd-o': 'far fa-hdd',
        'fas fa-header': 'fas fa-heading',
        'fas fa-heart-o': 'far fa-heart',
        'fas fa-hospital-o': 'far fa-hospital',
        'fas fa-hotel': 'fas fa-bed',
        'fas fa-hourglass-1': 'fas fa-hourglass-start',
        'fas fa-hourglass-2': 'fas fa-hourglass-half',
        'fas fa-hourglass-3': 'fas fa-hourglass-end',
        'fas fa-hourglass-o': 'far fa-hourglass',
        'fas fa-id-card-o': 'far fa-id-card',
        'fas fa-ils': 'fas fa-shekel-sign',
        'fas fa-image': 'far fa-image',
        'fas fa-inr': 'fas fa-rupee-sign',
        'fas fa-institution': 'fas fa-university',
        'fas fa-intersex': 'fas fa-transgender',
        'fas fa-jpy': 'fas fa-yen-sign',
        'fas fa-keyboard-o': 'far fa-keyboard',
        'fas fa-krw': 'fas fa-won-sign',
        'fas fa-legal': 'fas fa-gavel',
        'fas fa-lemon-o': 'far fa-lemon',
        'fas fa-level-down': 'fas fa-level-down-alt',
        'fas fa-level-up': 'fas fa-level-up-alt',
        'fas fa-life-bouy': 'far fa-life-ring',
        'fas fa-life-buoy': 'far fa-life-ring',
        'fas fa-life-saver': 'far fa-life-ring',
        'fas fa-lightbulb-o': 'far fa-lightbulb',
        'fas fa-line-chart': 'fas fa-chart-line',
        'fas fa-linkedin-square': 'fab fa-linkedin',
        'fas fa-linkedin': 'fab fa-linkedin-in',
        'fas fa-long-arrow-down': 'fas fa-long-arrow-alt-down',
        'fas fa-long-arrow-left': 'fas fa-long-arrow-alt-left',
        'fas fa-long-arrow-right': 'fas fa-long-arrow-alt-right',
        'fas fa-long-arrow-up': 'fas fa-long-arrow-alt-up',
        'fas fa-mail-forward': 'fas fa-share',
        'fas fa-mail-reply-all': 'fas fa-reply-all',
        'fas fa-mail-reply': 'fas fa-reply',
        'fas fa-map-marker': 'fas fa-map-marker-alt',
        'fas fa-map-o': 'far fa-map',
        'fas fa-meanpath': 'fab fa-font-awesome',
        'fas fa-meh-o': 'far fa-meh',
        'fas fa-minus-square-o': 'far fa-minus-square',
        'fas fa-mobile-phone': 'fas fa-mobile-alt',
        'fas fa-mobile': 'fas fa-mobile-alt',
        'fas fa-money': 'far fa-money-bill-alt',
        'fas fa-moon-o': 'far fa-moon',
        'fas fa-mortar-board': 'fas fa-graduation-cap',
        'fas fa-navicon': 'fas fa-bars',
        'fas fa-newspaper-o': 'far fa-newspaper',
        'fas fa-paper-plane-o': 'far fa-paper-plane',
        'fas fa-paste': 'far fa-clipboard',
        'fas fa-pause-circle-o': 'far fa-pause-circle',
        'fas fa-pencil-square-o': 'far fa-edit',
        'fas fa-pencil-square': 'fas fa-pen-square',
        'fas fa-pencil': 'fas fa-pencil-alt',
        'fas fa-photo': 'far fa-image',
        'fas fa-picture-o': 'far fa-image',
        'fas fa-pie-chart': 'fas fa-chart-pie',
        'fas fa-play-circle-o': 'far fa-play-circle',
        'fas fa-plus-square-o': 'far fa-plus-square',
        'fas fa-question-circle-o': 'far fa-question-circle',
        'fas fa-ra': 'fab fa-rebel',
        'fas fa-refresh': 'fas fa-sync',
        'fas fa-remove': 'fas fa-times',
        'fas fa-reorder': 'fas fa-bars',
        'fas fa-repeat': 'fas fa-redo',
        'fas fa-resistance': 'fab fa-rebel',
        'fas fa-rmb': 'fas fa-yen-sign',
        'fas fa-rotate-left': 'fas fa-undo',
        'fas fa-rotate-right': 'fas fa-redo',
        'fas fa-rouble': 'fas fa-ruble-sign',
        'fas fa-rub': 'fas fa-ruble-sign',
        'fas fa-ruble': 'fas fa-ruble-sign',
        'fas fa-rupee': 'fas fa-rupee-sign',
        'fas fa-s15': 'fas fa-bath',
        'fas fa-scissors': 'fas fa-cut',
        'fas fa-send-o': 'far fa-paper-plane',
        'fas fa-send': 'fas fa-paper-plane',
        'fas fa-share-square-o': 'far fa-share-square',
        'fas fa-shekel': 'fas fa-shekel-sign',
        'fas fa-sheqel': 'fas fa-shekel-sign',
        'fas fa-shield': 'fas fa-shield-alt',
        'fas fa-sign-in': 'fas fa-sign-in-alt',
        'fas fa-sign-out': 'fas fa-sign-out-alt',
        'fas fa-signing': 'fas fa-sign-language',
        'fas fa-sliders': 'fas fa-sliders-h',
        'fas fa-smile-o': 'far fa-smile',
        'fas fa-snowflake-o': 'far fa-snowflake',
        'fas fa-soccer-ball-o': 'far fa-futbol',
        'fas fa-sort-alpha-asc': 'fas fa-sort-alpha-down',
        'fas fa-sort-alpha-desc': 'fas fa-sort-alpha-up',
        'fas fa-sort-amount-asc': 'fas fa-sort-amount-down',
        'fas fa-sort-amount-desc': 'fas fa-sort-amount-up',
        'fas fa-sort-asc': 'fas fa-sort-up',
        'fas fa-sort-desc': 'fas fa-sort-down',
        'fas fa-sort-numeric-asc': 'fas fa-sort-numeric-down',
        'fas fa-sort-numeric-desc': 'fas fa-sort-numeric-up',
        'fas fa-spoon': 'fas fa-utensil-spoon',
        'fas fa-square-o': 'far fa-square',
        'fas fa-star-half-empty': 'far fa-star-half',
        'fas fa-star-half-full': 'far fa-star-half',
        'fas fa-star-half-o': 'far fa-star-half',
        'fas fa-star-o': 'far fa-star',
        'fas fa-sticky-note-o': 'far fa-sticky-note',
        'fas fa-stop-circle-o': 'far fa-stop-circle',
        'fas fa-sun-o': 'far fa-sun',
        'fas fa-support': 'far fa-life-ring',
        'fas fa-tablet': 'fas fa-tablet-alt',
        'fas fa-tachometer': 'fas fa-tachometer-alt',
        'fas fa-television': 'fas fa-tv',
        'fas fa-thermometer-0': 'fas fa-thermometer-empty',
        'fas fa-thermometer-1': 'fas fa-thermometer-quarter',
        'fas fa-thermometer-2': 'fas fa-thermometer-half',
        'fas fa-thermometer-3': 'fas fa-thermometer-three-quarters',
        'fas fa-thermometer-4': 'fas fa-thermometer-full',
        'fas fa-thermometer': 'fas fa-thermometer-full',
        'fas fa-thumb-tack': 'fas fa-thumbtack',
        'fas fa-thumbs-o-down': 'far fa-thumbs-down',
        'fas fa-thumbs-o-up': 'far fa-thumbs-up',
        'fas fa-ticket': 'fas fa-ticket-alt',
        'fas fa-times-circle-o': 'far fa-times-circle',
        'fas fa-times-rectangle-o': 'far fa-window-close',
        'fas fa-times-rectangle': 'fas fa-window-close',
        'fas fa-toggle-down': 'far fa-caret-square-down',
        'fas fa-toggle-left': 'far fa-caret-square-left',
        'fas fa-toggle-right': 'far fa-caret-square-right',
        'fas fa-toggle-up': 'far fa-caret-square-up',
        'fas fa-trash-o': 'far fa-trash-alt',
        'fas fa-trash': 'fas fa-trash-alt',
        'fas fa-try': 'fas fa-lira-sign',
        'fas fa-turkish-lira': 'fas fa-lira-sign',
        'fas fa-unsorted': 'fas fa-sort',
        'fas fa-usd': 'fas fa-dollar-sign',
        'fas fa-user-circle-o': 'far fa-user-circle',
        'fas fa-user-o': 'far fa-user',
        'fas fa-vcard-o': 'far fa-address-card',
        'fas fa-vcard': 'fas fa-address-card',
        'fas fa-video-camera': 'fas fa-video',
        'fas fa-vimeo': 'fab fa-vimeo-v',
        'fas fa-volume-control-phone': 'fas fa-phone-volume',
        'fas fa-warning': 'fas fa-exclamation-triangle',
        'fas fa-wechat': 'fab fa-weixin',
        'fas fa-wheelchair-alt': 'fab fa-accessible-icon',
        'fas fa-window-close-o': 'far fa-window-close',
        'fas fa-won': 'fas fa-won-sign',
        'fas fa-y-combinator-square': 'fab fa-hacker-news',
        'fas fa-yc-square': 'fab fa-hacker-news',
        'fas fa-yc': 'fab fa-y-combinator',
        'fas fa-yen': 'fas fa-yen-sign',
        'fas fa-youtube-play': 'fab fa-youtube',
        'fas fa-youtube-square': 'fab fa-youtube'
    }

    FA_MANUAL_REVIEW = [
        'fa-lg',
        'fa-2x',
        'fa-3x',
        'fa-4x',
        'fa-5x',
        'fa-fw',
        'fa-li',
        'fa-border',
        'fa-pull-right',
        'fa-pull-left',
        'fa-spin',
        'fa-pulse',
        'fa-rotate',
        'fa-flip',
        'fa-stack',
        'fa-inverse',
    ]
    
    @staticmethod
    def pathCheck (dir, createBackup):
        for (dirpath, dirnames, filenames) in walk(dir):
            for filename in filenames:
                FontAwesome4To5.fileCheck(dir+'/'+filename, createBackup)
            break
        
    @staticmethod
    def fileCheck (fullpath, createBackup):
        if (fullpath[-3:] == "bak"):
            return
        
        if (createBackup):
            copyfile(fullpath, fullpath+'.bak')
        
        with open(fullpath, 'r+') as file:
            content = file.read()
            file.seek(0)
            content = content.replace('fa fa-', 'fas fa-')
            for attribute, value in FontAwesome4To5.FA_ICONS.iteritems():
                content = content.replace(attribute, value)
            
            # manual review
            for value in FontAwesome4To5.FA_MANUAL_REVIEW.iteritems():
                stackCount = content.count(value)
                if (stackCount > 0):
                    print str(stackCount)+" "+value+" in "+fullpath

            file.write(content)